-- Festa Major Blancs i Blaus · Granollers 2026
-- Schema de Supabase (PostgreSQL)

-- ===== CREAR TABLAS =====

CREATE TABLE activitats (
  id SERIAL PRIMARY KEY,
  dia TEXT NOT NULL,
  hora TEXT NOT NULL,
  hora_sort TEXT NOT NULL,
  nom TEXT NOT NULL,
  lloc TEXT NOT NULL,
  organitzador TEXT,
  preu TEXT,
  descripcio TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE inscripcions (
  id SERIAL PRIMARY KEY,
  activitat_id INTEGER NOT NULL REFERENCES activitats(id) ON DELETE CASCADE,
  nom_cognom TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT NOW()
);

-- ===== CREAR ÍNDICES =====
CREATE INDEX idx_activitats_dia ON activitats(dia);
CREATE INDEX idx_activitats_hora_sort ON activitats(hora_sort);
CREATE INDEX idx_inscripcions_activitat ON inscripcions(activitat_id);

-- ===== HABILITAR RLS =====
ALTER TABLE activitats ENABLE ROW LEVEL SECURITY;
ALTER TABLE inscripcions ENABLE ROW LEVEL SECURITY;

-- ===== POLÍTICAS RLS =====

-- activitats: SELECT público (anon)
CREATE POLICY activitats_select_policy ON activitats
  FOR SELECT
  USING (true);

-- inscripcions: SELECT público (anon)
CREATE POLICY inscripcions_select_policy ON inscripcions
  FOR SELECT
  USING (true);

-- inscripcions: INSERT público (anon)
CREATE POLICY inscripcions_insert_policy ON inscripcions
  FOR INSERT
  WITH CHECK (true);

-- inscripcions: DELETE público (anon)
CREATE POLICY inscripcions_delete_policy ON inscripcions
  FOR DELETE
  USING (true);

-- ===== INSERTAR ACTIVIDADES =====

INSERT INTO activitats (dia, hora, hora_sort, nom, lloc, organitzador, preu, descripcio) VALUES

-- DISSABTE 22
('Dissabte 22','9.01h','09:01','Caminada per anar escalfant la festa - Inici del viatge a Blaus','Plaça de la Porxada','Blaus - Amics de Ponent','Gratuïta','Inscripció gratuïta mitja hora abans a la mateixa plaça'),
('Dissabte 22','9.03h','09:03','El Blau més híbrid del país de les meravelles','Plaça de l''Església','Blaus - Blaus Híbrids','','Acte esportiu híbrid amb estacions puntuables. Majors d''edat, inscripcions a les 9h'),
('Dissabte 22','10.32h','10:32','Esmorzar potent amb els de Ponent','Plaça de les Olles','Blaus - Amics de Ponent','6€','Omple la panxa abans de caure pel forat'),
('Dissabte 22','11h','11:00','El Colom t''ensenya el seu ball','Plaça de la Porxada','Colom de Granollers','',''),
('Dissabte 22','11h','11:00','Taller de castells - Enfaixa''t amb els Xics','Plaça de Maluquer i Salvador','Xics de Granollers','','Taller apte per a totes les edats. Puja, fes l''aleta i fes pinya'),
('Dissabte 22','11.03h','11:03','La minicorda','Carrer d''Anselm Clavé','Blaus - La Corda Blava','','Taller pràctic infantil de 7 a 12 anys. Cal portar guants i calçat esportiu'),
('Dissabte 22','11.30h','11:30','Xops! - Festa de l''aigua','Plaça de la Corona','Drac de Granollers','','L''aigua ha tornat. Vine a ruixar-te!'),
('Dissabte 22','12h','12:00','El Despertar de la Cuca (CU22PRX)','Plaça de la Porxada','Blancs / La Cuca dels Blancs','','La Cuca torna a despertar acompanyada de tota l''aviació blanca'),
('Dissabte 22','12.30h','12:30','Check in (CB22PRX1) - Vermut i música en directe','Plaça de la Porxada','Blancs','','Primer segell del passaport blanc!'),
('Dissabte 22','12.30h','12:30','Geocatching Petit Príncep (PG22PRX)','Plaça de la Porxada','Blancs - Pàgines en blanc','','El Petit Príncep ha quedat atrapat. Segueix les pistes diàries'),
('Dissabte 22','16h','16:00','Correaigua infantil - Es busca aigüer (CA22MLQ1)','Plaça de Maluquer i Salvador','Blancs - Correaigua','','Per a menors d''11 anys. Porta el banyador'),
('Dissabte 22','16.31h','16:31','Electropark: Down The Rabbit Hole - DJ LeTung','Parc de Torras Villà','Blaus - ElectroPark','',''),
('Dissabte 22','16.33h','16:33','No-Blaugnasad','Plaça de l''Església','Blaus - Blauceltes','','Feliç, feliç No-Blaugnasad...'),
('Dissabte 22','17h','17:00','Correaigua infantil (CA22MLQ2) - De 12 a 17 anys','Plaça de Maluquer i Salvador','Blancs - Correaigua','','De 12 a 17 anys. Porta banyador'),
('Dissabte 22','18h','18:00','Correaigua (CA22MLQ3) - Majors de 18 anys','Plaça de Maluquer i Salvador','Blancs - Correaigua','','Majors de 18 anys. Porta banyador'),
('Dissabte 22','18.30h','18:30','Arriba la Mulassa, arriba la Festa Major!','Carrer Enric Prat de la Riba','L''Olla dels Pobres - Mulassa','','La Mulassa visita el barri de Sota el Camí Ral'),
('Dissabte 22','19h','19:00','Venda de tiquets del Correbars (EB22PTF1)','Plaça de Folch i Torres','Blancs - Elefant Blanc','9€','Majors de 18 anys. 3 tiquets màxim per persona'),
('Dissabte 22','19h','19:00','Sopar Blanc d''Alta Volada (GB22PSN)','Plaça de Catalunya','Blancs - Guapes','','Dress code blanc rigorós, taules de 10 persones, cadascú porta el seu sopar'),
('Dissabte 22','19.02h','19:02','Amics infernals: Plantada de bèsties','Plaça de Can Trullàs','Blaus - Gralla de Foc / Costaleros del Farras','','Bèsties del jardí de les meravelles'),
('Dissabte 22','19.07h','19:07','Electropark: Down The Rabbit Hole - DJ NocturN','Parc de Torras Villà','Blaus - ElectroPark','',''),
('Dissabte 22','19.30h','19:30','Correbars de l''Elefant Blanc (EB22PTF2)','Plaça de Folch i Torres','Blancs - Elefant Blanc','9€','Majors de 18 anys. Necesita tiquet previ. Amb Tirand lo Band'),
('Dissabte 22','19.30h','19:30','Festa de l''escuma blanc-i-blava','Plaça de les Hortes','AV Sota el Camí Ral','','Vine amb banyador i tovallola'),
('Dissabte 22','20.35h','20:35','Nit de Botes - segueix el conill!','Plaça de les Olles','Blaus - Templers Blaus','','Música alternativa amb la furgoneta de Templers. Porta la teva bota'),
('Dissabte 22','20.39h','20:39','Amics infernals: Cercavila','Plaça de Can Trullàs','Blaus - Gralla de Foc / Costaleros del Farras','',''),
('Dissabte 22','20.58h','20:58','Electropark: Down The Rabbit Hole - Frigolum b2b Eagle','Parc de Torras Villà','Blaus - ElectroPark','5€ (sopar)','Hi haurà sopar!'),
('Dissabte 22','21.34h','21:34','Un viatge de conya al País Blau - Tapeo i podcast','Plaça de Barangé','Blaus - La Conya','5€','Tapeo escoltant el pòdcast amb espectacle i PD Hada'),
('Dissabte 22','21.35h','21:35','Amics infernals: Lluïment final','Plaça de Barangé','Blaus - Gralla de Foc / Costaleros del Farras','',''),
('Dissabte 22','21.59h','21:59','EAUfòria, el concurs','Plaça de Perpinyà','Blaus - Rauxats','','A partir de 16 anys. Grups de 3 a 4 persones. Inscripcions prèvies a @rauxats'),
('Dissabte 22','22h','22:00','Què volem? (DB22PRX) - Projecció','Plaça de la Porxada','Blancs - Dissonància Blanca','',''),
('Dissabte 22','22.05h','22:05','No-Blaugnasad amb Burxa, As de Covers, IguanaFine i DJ Enric Font','Plaça de l''Església','Blaus - Blauceltes','',''),
('Dissabte 22','22.33h','22:33','Caient al forat: que li treguin el tap! Amb DJ Conillet','C. Sant Roc / Anselm Clavé','Blaus - Proyecto Eco / La Fura dels Blaus','','Tots estem bojos aquí!'),
('Dissabte 22','23h','23:00','Concert amb Sicuta i PDTes (CB22PRX2)','Plaça de la Porxada','Blancs','','El grup de versions que totes estàvem esperant'),
('Dissabte 22','23.07h','23:07','Electropark: Down The Rabbit Hole - Hector','Parc de Torras Villà','Blaus - ElectroPark','',''),
('Dissabte 22','00h','24:00','L''After del Correbars by Hardblancs (HB22PCS)','Plaça de Pau Casals','Blancs - Hardblancs','','Passatgers a bord: tecnasso a cabina'),
('Dissabte 22','01.11h','25:11','Electropark: Down The Rabbit Hole - Raul Mezcolanza','Parc de Torras Villà','Blaus - ElectroPark','',''),

-- DIUMENGE 23
('Diumenge 23','7.37h','07:37','Ioga al jardí amb Blaus Híbrids','Parc de Torras Villà','Blaus - Blaus Híbrids','','Per a tots els cossos i totes les edats. Cal portar màrfega. Sense inscripcions'),
('Diumenge 23','9h','09:00','Street Rogaine (BP23MLQ) - Cursa d''orientació','Plaça de Maluquer i Salvador','Blancs - Blancperduts','5€','Equips de 2 a 5 persones. Modalitats familiar i competitiva. Dorsals a les 8.30h'),
('Diumenge 23','10h','10:00','Pedalada Solidària de Festa Major','Plaça de la Corona','Granollers Pedala','Donació voluntària','Majors de 8 anys. Casc obligatori menors 16 anys. Sortida a les 10.30h'),
('Diumenge 23','10.01h','10:01','Bitlles catalanes, el croquet blau de la Reina','Parc de Torras Villà','Blaus - Foteu-li Canya','','Jocs al Jardí de les Meravelles'),
('Diumenge 23','10.06h','10:06','Trobada de gegantons! Plantada i activitats infantils','Plaça de la Porxada','Blaus - Gegantons','','On els petits es fan grans!'),
('Diumenge 23','11.35h','11:35','Cercavila 30 aniversari Gegantons: Un, dos, tres, avancem!!!','Plaça de la Porxada','Blaus - Gegantons','',''),
('Diumenge 23','11.38h','11:38','L''Hora del Vermut - Concert de Cul de Sac','Parc de Torras Villà','Blaus - Foteu-li Canya','',''),
('Diumenge 23','12h','12:00','Pintxo Pote Musical (KZ23PTF)','Plaça de Folch i Torres','Blancs - Kompartsa Zuria','','La plaça es converteix en una taverna basca. Bon menjar, bon beure, bona música'),
('Diumenge 23','16.30h','16:30','Toc d''inici de la Festa Major','Plaça de la Porxada','Blancs i Blaus','','Vine amb el teu instrument!'),
('Diumenge 23','17h','17:00','Cerimònia d''inici de festes i el Repte','Plaça de la Corona','Comissió de la Festa Major','','Lluïment dels grups festius i els Blancs repten els Blaus'),
('Diumenge 23','22.04h','22:04','Correbars - seguint el conill (Blaus Street Music Band)','Plaça Pau Casals','Blaus - Blaus Street Music Band','','Majors de 18 anys. Reserves a @blausbsmb'),
('Diumenge 23','00h','24:00','Bingo musical amb PD TropicalTes','Plaça de la Porxada','Blancs i Blaus','1€','Tiquets limitats, es vendran al costat de l''escenari quan acabi el sopar de colles'),

-- DILLUNS 24
('Dilluns 24','10h','10:00','Quadern de vol (SK24BTG) - Busca objectes voladors als comerços','Botigues del centre','Blancs - Stick&Blancs','','Compra el quadern a la botiga i busca els objectes amagats als comerços'),
('Dilluns 24','10h','10:00','Granollers vola amb els Gegantons Blancs (GT24PRX)','Plaça de la Porxada','Blancs - Gegantons','','Supera les proves, descobreix aeroports i vola ben amunt! De 2 a 18 anys'),
('Dilluns 24','10h','10:00','Penja el teu Ema i demana el teu desig! (SH24PRT)','Carrer del Portalet','Blancs - Shiro','','Acte de dilluns 24 a dimecres 26 d''agost'),
('Dilluns 24','10.30h','10:30','Escape Plane: Aterra com puguis! (PN24NB1) - ScapeRoom','Roca Umbert. Nau B1','Blancs - Paranoia','','Inscripcions a @paranoia.blancs. Tot el dia volant'),
('Dilluns 24','10.35h','10:35','Reserva plaça pel corral dels Torets','C. Anselm Clavé (davant Museu)','Blaus - Torets','','Estalvia''t la cua de la Prèvia i dels Torets embolats'),
('Dilluns 24','15.30h','15:30','Escape Plane: Aterra com puguis! (PN24NB1) - Tarda','Roca Umbert. Nau B1','Blancs - Paranoia','','Inscripcions a @paranoia.blancs'),
('Dilluns 24','16.31h','16:31','La Tribuna - ones radiofòniques a l''altra banda del mirall','Sala Francesc Tarafa','Blaus - B.A.R.','','Producte radiofònic sense processar. blaus.cat'),
('Dilluns 24','16.59h','16:59','Tic, tac... Tea? L''hora blava','Sala Francesc Tarafa','Blaus - L''Orbital','','Passis a les 17, 18 i 19h. Res és el que sembla'),
('Dilluns 24','17.02h','17:02','La dansa de les feres - Taller de dansa folk','Parc de Congost','Blaus - Les Feres','','Activitat familiar i reivindicativa. Ballem!'),
('Dilluns 24','17.30h','17:30','Sala d''espera: Gimcana 10 anys Zuteko (ZK24MLQ)','Plaça de Maluquer i Salvador','Blancs - Zuteko','','Supera les proves, segella el passaport i celebra 10 anys de Zuteko'),
('Dilluns 24','17.30h','17:30','El cel crema en blanc: Plantada de bèsties (GS24ESG1)','Plaça de l''Església','Blancs - La Guspira','','Les bèsties blanques aterren a l''Aeroport Blanc Amador Galí'),
('Dilluns 24','17.57h','17:57','Més bojos que el Barreter - Remember Blaus (80s/90s/2000s)','Plaça de Folch i Torres','Blaus - Remember Blaus','','Al país blau el temps va enrere!'),
('Dilluns 24','17.59h','17:59','Meravelles al parc - Inauguració','Parc de Torras Villà','Blaus - Mesclat de Blaus','','La inauguració d''un acte històric'),
('Dilluns 24','18.02h','18:02','Les Feres tornen al país de les meravelles! Cercavila','Parc de Congost','Blaus - Les Feres','','Cercavila reivindicativa i festiva'),
('Dilluns 24','18.05h','18:05','8è Blaus Sound System Festival - Júlia Soler','Plaça Barangé','Blaus - Jamaican Blaus','','No miris el rellotge!'),
('Dilluns 24','18.31h','18:31','Reserva plaça pel corral dels Torets (tarda)','Parc de Torras Villà','Blaus - Torets','',''),
('Dilluns 24','18.35h','18:35','Meravelles al parc - Tarda','Parc de Torras Villà','Blaus - Mesclat de Blaus','','Més de 20 colles de Blaus mesclades! Participa!'),
('Dilluns 24','19h','19:00','Quina Vella (LV24ESG)','Plaça de l''Església','Blancs - La vella','2€','Vine a jugar a la Quina de la Vella! Grans premis i música en directe'),
('Dilluns 24','19h','19:00','Bingo: Boarding Pass (SR24OLL1) - KPOP bingo musical','Plaça de les Olles','Blancs - Sweet Rebels','0,5€','Cartrons limitats per ordre d''arribada'),
('Dilluns 24','19.33h','19:33','Concert amb En Diskordia','Plaça de la Porxada','Blaus - Blau Feuer','','No hi ha meravella blava sense discòrdia!'),
('Dilluns 24','19.57h','19:57','8è Blaus Sound System Festival - Endemic Sound','Plaça Barangé','Blaus - Jamaican Blaus','5€ (sopar)','Hi haurà botifarres!'),
('Dilluns 24','20h','20:00','Sala d''espera: Jam Blanca (DB24MLQ)','Plaça de Maluquer i Salvador','Blancs - Dissonància Blanca','','Porta l''instrument! Jam session oberta'),
('Dilluns 24','20h','20:00','Assaig especial de Festa Major - Acosta''t als castells','La Troca, Centre de Cultura Popular','Xics de Granollers','','Vine a veure''ns i participa en la pinya! #35xics'),
('Dilluns 24','20.02h','20:02','Meravelles al parc - Sopar','Parc de Torras Villà','Blaus - Mesclat de Blaus','5€ (sopar)','T''estem esperant! Et quedaràs sense hamburguesa?'),
('Dilluns 24','20.30h','20:30','El cel crema en blanc: Sopar (GS24ESG2)','Plaça de l''Església','Blancs - La Guspira','5€','Sopar de brasa per anar escalfant la plaça'),
('Dilluns 24','21h','21:00','Sala d''espera: El sopar de la revolta (NB24MLQ1)','Plaça de Maluquer i Salvador','Blancs - Nimfes','8€','Servei de sopar vegà i sense gluten'),
('Dilluns 24','21.14h','21:14','La Principal Blava - Ballada de sardanes','Plaça de la Porxada','Blaus - La Principal Blava','','Cobla meravellosament Blava!'),
('Dilluns 24','21.56h','21:56','Escalabirres','Plaça de Barangé','Blaus - Blauchama','','A partir de 18 anys. Roba còmoda que es pugui mullar. Inscripcions a les 19h'),
('Dilluns 24','22h','22:00','Disco: Jet lag (SR24OLL2) - K-Pop','Plaça de les Olles','Blancs - Sweet Rebels','','3a edició de la disco de K-Pop'),
('Dilluns 24','22.02h','22:02','8è Blaus Sound System Festival - Rebelmadiaq Sound','Plaça Barangé','Blaus - Jamaican Blaus','','El batec del cau'),
('Dilluns 24','22.05h','22:05','Meravelles al parc - El judici de la reina','Parc de Torras Villà','Blaus - Mesclat de Blaus','','Ajuda-la a dictar sentència!'),
('Dilluns 24','22.30h','22:30','El cel crema en blanc (GS24ESG3) - Cercavila de foc','Plaça de l''Església','Blancs - La Guspira','','La Guspira surt volant per Festa Major amb foc, ritme i molta festa!'),
('Dilluns 24','22.46h','22:46','Meravelles al parc - Foc en Blau','Parc de Torras Villà','Blaus - Mesclat de Blaus','','Foc en Blau. En acabar, passeja pel parc il·luminat'),
('Dilluns 24','22.56h','22:56','Concert amb Siderland i DJ Murci b2b Brètol','Plaça de la Porxada','Blaus - Blau Feuer','','Música electrònica que et farà sortir del cau!'),
('Dilluns 24','23h','23:00','Sala d''espera: Revolta Nimfa (NB24MLQ2)','Plaça de Maluquer i Salvador','Blancs - Nimfes','','Karaoke, banda en directe i PD Piruleta. Inscripcions 1h abans'),
('Dilluns 24','23.33h','23:33','Meravelles al parc - DJ Knopfler','Parc de Torras Villà','Blaus - Mesclat de Blaus','','Deixa''t moure a ritme de la DJ Knopfler'),
('Dilluns 24','00h','24:00','Concert amb Gregotechno i DJ Guspi (CB24ESG)','Plaça de l''Església','Blancs','','Música electrònica fusionada amb cants gregorians'),
('Dilluns 24','00.07h','24:07','8è Blaus Sound System Festival - Pupa Congo & Nou Art Records','Plaça Barangé','Blaus - Jamaican Blaus','','Més enllà de les hores'),

-- DIMARTS 25
('Dimarts 25','7.31h','07:31','Ioga al jardí amb Blaus Híbrids','Parc de Torras Villà','Blaus - Blaus Híbrids','','Per a tots els cossos i totes les edats. Cal portar màrfega. Sense inscripcions'),
('Dimarts 25','10h','10:00','Vine a fer la Mitja! (EB25MLQ)','Plaça de Maluquer i Salvador','Blancs - Elefant Blanc','','Fes mitja o ganxet mentre esperes l''avionet!'),
('Dimarts 25','10h','10:00','Volem pintar! (AW25MLQ) - Taller d''art','Plaça de Maluquer i Salvador','Blancs - Art & White','','Places limitades. Decora, munta i fes volar la teva Espurna dels Blancs!'),
('Dimarts 25','10.30h','10:30','La confetinada blanca i blava','Plaça de la Porxada','Ajuntament de Granollers','','Festa de confeti amb l''animació del Pep Callau i els Pepsicolen'),
('Dimarts 25','10.30h','10:30','Escape Plane: Aterra com puguis! (PN25NB1) - ScapeRoom','Roca Umbert. Nau B1','Blancs - Paranoia','','Inscripcions a @paranoia.blancs. Tot el dia volant'),
('Dimarts 25','10.30h','10:30','Assaya amb Blancstons (BT25PRC) - Taller de bastons','Plaça de Perpinyà','Blancs - Blancstons','','Per a totes les edats. Vols picar bastons al ritme de Rock&Roll?'),
('Dimarts 25','11h','11:00','1r Campionat Mundial de Pedra, Paper, Tisora (PP25MLQ)','Plaça de Maluquer i Salvador','Blancs - PPT''S','','Grups de 3 persones. Inscripcions a partir de les 10.30h'),
('Dimarts 25','12h','12:00','Vermut amb Michelin Blanc (MB25MLQ)','Plaça de Maluquer i Salvador','Blancs - Michelin Blanc','3€','Servei de tapes amb opció vegana, vegetariana i sense gluten'),
('Dimarts 25','15.30h','15:30','Escape Plane: Aterra com puguis! (PN25NB1) - Tarda','Roca Umbert. Nau B1','Blancs - Paranoia','','Inscripcions a @paranoia.blancs'),
('Dimarts 25','16.57h','16:57','L''Hora del Tardeo - Música tradicional','Plaça de Maluquer i Salvador','Blaus - Clave de Fro','','El ritme del país blau'),
('Dimarts 25','17h','17:00','Art and Wine (AW25PRC) - Brodar o pintar amb vi','Plaça de Perpinyà','Blancs - Art & White','8€','Majors de 18 anys. Tiquets a les 16h. Per ordre d''arribada'),
('Dimarts 25','17h','17:00','Pintura al Vol Infantil: Defensa l''Aeroport (PD25OLL1)','Plaça de les Olles','Blancs - La Pedrera','','Fins a 18 anys. Grups de 5 persones. Roba que es pugui embrutar'),
('Dimarts 25','17.30h','17:30','Cercavila infantil de Festa Major','Plaça de la Corona','Comissió de la Festa Major','',''),
('Dimarts 25','18h','18:00','Lluïment dels elements festius de la cercavila infantil','Plaça de la Porxada','Comissió de la Festa Major','',''),
('Dimarts 25','18.04h','18:04','El Jardí de les Meravelles - Blaus 360','Plaça Barangé','Blaus - Blaus 360','','Accepta el repte, recupera forces amb un bon sopar i acaba la nit amb bona música'),
('Dimarts 25','18.30h','18:30','El bou s''empassa la festa (PM25PEX)','Plaça del Peix','Blancs - Patam','','Majors 18 anys. Inscripcions fins al dia abans a @patamblanques'),
('Dimarts 25','19h','19:00','Pintura al Vol (PD25OLL2) - Batalla de pintura majors','Plaça de les Olles','Blancs - La Pedrera','','A partir de 18 anys. Grups de 5 persones. Roba que es pugui embrutar'),
('Dimarts 25','19h','19:00','La Millor Croqueta de Granollers (CR25PTV)','Parc de Torras Villà','Blancs - Croquetes Blanques','7€','4a edició del concurs! Inclou 5 croquetes i copa de vi o aigua'),
('Dimarts 25','19h','19:00','Visita guiada a la muralla medieval de Granollers','L''Adoberia','Ajuntament de Granollers','Gratuïta amb reserva','Horaris 19h, 20h, 22h i 23h. Recorregut 800m, 45 minuts. Reserva a granollers.cat/patrimoni'),
('Dimarts 25','19.07h','19:07','Missió: Allibera al barreter! - Joc competició','Plaça de Barangé','Blaus - Blaus 360','','A partir de 18 anys. Grups de 2 a 4 persones. Inscripcions a partir de les 18.30h'),
('Dimarts 25','19.30h','19:30','Enlaira''t amb Les Guapes (GB25CRT)','Carrer d''Anselm Clavé','Blancs - Guapes','','Us donem la benvinguda a l''Aeroport Blanc Amador Galí'),
('Dimarts 25','19.30h','19:30','Assaig de Festa Major - Xics de Granollers','La Troca, Centre de Cultura Popular','Xics de Granollers','','Vine a veure''ns i participa dels castells. #35xics'),
('Dimarts 25','20h','20:00','Salsa Blanca: vol 4 (SB25PRC) - Balls llatins','Plaça de Perpinyà','Blancs - Salsa Blanca','','Classe magistral de balls llatins a ritme de DJ Victor Suco'),
('Dimarts 25','20.30h','20:30','Combat de glosa de Granollers (BA25ESG)','Plaça de l''Església','Blancs - Blancs d''arrel','','Corrandes, nyacres i garrotins. Inscripcions a @blancsdarrel'),
('Dimarts 25','20.33h','20:33','Obrim el Pique de Gralles 2026 - Els cairons','Plaça de Maluquer i Salvador','Blaus - Clave de Fro','','Música tradicional, i la nostàlgia de l''any passat'),
('Dimarts 25','20.47h','20:47','La prèvia dels Torets Embolats (fins 1,20m)','Plaça de Can Trullàs','Blaus - Torets','','Fins a 1,20m d''alçada. Reserva l''entrada dilluns!'),
('Dimarts 25','21h','21:00','Blankinis (CB25PTF) - Servei de bikinis','Plaça de Perpinyà','Blancs','2,5€','Servei de bikinis a la terminal. Opció vegetariana i sense gluten'),
('Dimarts 25','21h','21:00','Punk al Patufet: No volem el limitador fest II (RP25PTF)','Plaça de Folch i Torres','Blancs - Rock als Porks','','Punk underground. Primal HC, Enyor, Residuos Permanentes i més!'),
('Dimarts 25','21.02h','21:02','Banquet de les meravelles (Blaus 360)','Plaça de Barangé','Blaus - Blaus 360','7,5€','Tiquets a partir de les 20h a la mateixa plaça'),
('Dimarts 25','21.14h','21:14','Gimcana nocturna amb les Blauchirris','Plaça de la Porxada','Blaus - Blauchirris','','A partir de 18 anys. Grups de 8 a 10 persones. Inscripcions de 17 a 20h'),
('Dimarts 25','21.17h','21:17','Sortida dels Torets Embolats (fins 1,60m)','Plaça de Can Trullàs','Blaus - Torets','','Màxim 1,60m d''alçada. Menors de menys d''1,40m han d''anar amb un adult'),
('Dimarts 25','21.31h','21:31','Pique de Gralles 2026 - Concurs','Plaça de Maluquer i Salvador','Blaus - Clave de Fro','','Música tradicional, el concurs al país blau'),
('Dimarts 25','22h','22:00','Cercavila Guita Jove','Plaça de la Corona','Blaus - Guita Jove','',''),
('Dimarts 25','22.02h','22:02','Torets Embolats Joves (superiors a 1,60m)','Plaça de Can Trullàs','Blaus - Torets','','Menors d''edat amb alçada superior a 1,60m. Indispensable DNI'),
('Dimarts 25','22.05h','22:05','Concert amb Els Pipes i DJ Turmo','Plaça de Barangé','Blaus - Blaus 360','',''),
('Dimarts 25','22.30h','22:30','XXX - 30 anys Dames de foc (DF25PTV)','Parc de Torras Villà','Blancs - Dames de foc','','30 anys per recordar i celebrar'),
('Dimarts 25','23.29h','23:29','Concert del Pique de Gralles 2026 - La Cosina i DJ Pikes','Plaça de Maluquer i Salvador','Blaus - Clave de Fro','','Música tradicional, ballem fins al final al país blau'),
('Dimarts 25','00.03h','24:03','Concert amb Caipirinyes','Plaça de la Porxada','Blaus - Blauchirris','','Les versions més meravelloses del país!'),
('Dimarts 25','00.15h','24:15','Concert amb OKDW i DJ Tiwi (CB25ESG)','Plaça de l''Església','Blancs','','Groove, R&B, pop amb personalitat pròpia'),
('Dimarts 25','1.11h','25:11','2000.mp3 - Flow 2000, electrolatino i pop','Plaça de la Porxada','Blaus - Blaus mp3','','Suc de taronja i mandarina, la millor festa s''aproxima...'),

-- DIMECRES 26
('Dimecres 26','10h','10:00','Alça el vol amb la Força Blanca (CB26CRN)','Plaça de la Corona','Blancs','','Activitat participativa per a totes les edats'),
('Dimecres 26','10h','10:00','Enlaira''t jugant (CC26CRN) - Jocs infantils 0-10 anys','Plaça de la Corona','Blancs - Cuquetes i Cucots','','Matinal de jocs infantils de 0 a 10 anys'),
('Dimecres 26','10.04h','10:04','Escalaquintos - Castell de capses','Parc de Torras Villà','Blaus - Farretes','','De 6 a 12 anys. Grups de 3 persones. Preinscripció a @farretesblaus'),
('Dimecres 26','12.07h','12:07','Vermut i sifó amb Xavi Rizzo, La Gramola Humana','Plaça de la Porxada','Blaus - Vermutaires','','La bogeria del migdia!'),
('Dimecres 26','17.54h','17:54','Cluedo gegant: Qui ha matat a la Reina Blanca?','Plaça de Maluquer i Salvador','Blaus - Xauxa Blava','','Grups de 3 a 6 persones a partir de 16 anys. Entrada lliure de 17.54 a 20.15h'),
('Dimecres 26','17.57h','17:57','El jardí més canalla del país de les meravelles - Manualitats infantils','Parc de Torras Villà','Blaus - Canalla Blava','','Entre papers, colors i molta fantasia'),
('Dimecres 26','17.59h','17:59','Campionat de Puzles Blancs vs Blaus','C. Anselm Clavé / Plaça de la Corona','Blaus - Club de Rol Menrood','',''),
('Dimecres 26','18h','18:00','Alcem el vol! (DM26PTV) - Dametes','Parc de Torras Villà','Blancs - Dametes','','Les Dametes alcen el vol per travessar els núvols'),
('Dimecres 26','18.08h','18:08','El regne de Les Blaves - Gimcana','Plaça de Can Trullàs','Blaus - Les Blaves','','A partir dels 6 anys. Grups de 4 persones. Preinscripció a @lesblaves'),
('Dimecres 26','18.15h','18:15','Assaig obert del Ball de Donzelles de Granollers','Plaça de la Porxada','Esbart Dansaire','',''),
('Dimecres 26','18.30h','18:30','Correvent infantil','Carrer d''Anselm Clavé','Comissió de la Festa Major','','Fins a 11 anys i a partir d''1,10m d''alçada. Sorteig a les 18h'),
('Dimecres 26','18.30h','18:30','Mini Disco (DL26PCS)','Plaça Pau Casals','Blancs - Dents de llet','','Coreografies, festa i diversió!'),
('Dimecres 26','18.31h','18:31','Torneig de Blauspong','Plaça de les Olles','Blaus - Blau Feuer','5€','Majors de 18 anys. Inscripcions a les 17.30h. Imprescindible portar got'),
('Dimecres 26','18.34h','18:34','Joc de Clans. You''ll never play alone','Plaça de Barangé','Blaus - MacNessie','','Infantil (3-10 anys) o júnior (a partir d''11 anys)'),
('Dimecres 26','18.35h','18:35','L''Orquestra de les Meravelles en concert','Plaça de la Caserna','Blaus - Blautatuna','','Descobreix el nou repertori'),
('Dimecres 26','19h','19:00','Correvent (a partir de 12 anys)','Carrer d''Anselm Clavé','Comissió de la Festa Major','','A partir de 12 anys i d''1,10m d''alçada'),
('Dimecres 26','19h','19:00','Ballada de danses mediterrànies','Plaça de la Porxada','Passaltpas','',''),
('Dimecres 26','19.02h','19:02','La meravellosa cursa bàrbara - Carro race','Plaça del Peix','Blaus - Blaubaricum','','A partir de 18 anys. Grups de 2 a 4 persones. Casc obligatori. Inscripcions de 16.30 a 18h'),
('Dimecres 26','19.05h','19:05','Passacarrers amb l''Orquestra de les Meravelles','Plaça de la Caserna','Blaus - Blautatuna','','Te les sabràs totes, una meravella!'),
('Dimecres 26','19.30h','19:30','Va de Rams - Entrega de rams a les gegantes','Cantonada Fonda Europa','Amics dels Gegants i Capgrossos','','Recorregut fins a la Porxada'),
('Dimecres 26','19.30h','19:30','Acudits al vol (BH26PTF) - Espectacle de comèdia','Plaça de Folch i Torres','Blancs - Blahahahancs','','Amb Marma Corales, Godai Garcia i Alba Segarra'),
('Dimecres 26','19.30h','19:30','Vespreig de les Espurnes (EP26PCS1)','Plaça de Pau Casals','Blancs - Espurnes','','Porta el teu sopar i les espurnes hi posem la música'),
('Dimecres 26','20.06h','20:06','Cercavila dels Sambeiros','Plaça de la Caserna','Blaus - Sambeiros do Rio Congost','','Portem el ritme al país de les meravelles'),
('Dimecres 26','20.30h','20:30','Sopar a la fresca - Entrepà de botifarra','Plaça de Perpinyà','Esbart Dansaire','','Opció vegetariana. Tiquets a partir de les 20h'),
('Dimecres 26','21h','21:00','Rodafoc (EP26PCS2)','Plaça Pau Casals','Blancs - Espurnes','','Les espurnes s''enlairen un any més omplint el cel de foc'),
('Dimecres 26','21h','21:00','Arribada dels gegants de la ciutat a l''Ajuntament','Plaça de la Porxada','Amics dels Gegants i Capgrossos','',''),
('Dimecres 26','21h','21:00','Sopar amb Michelin Blanc (MB26PTF)','Plaça de Folch i Torres','Blancs - Michelin Blanc','5€','Servei de tapes amb opció vegana, vegetariana i sense gluten'),
('Dimecres 26','21.01h','21:01','Blaus Endins - El musical d''Alícia','Plaça de l''Església','Blaus','',''),
('Dimecres 26','21.30h','21:30','Enlaira''t al vol (XL26PTV) - Dametes XL','Parc de Torras Villà','Blancs - Dametes XL','','Llum, color i emoció'),
('Dimecres 26','21.30h','21:30','Stage: Fighting Beyond Heaven (SR26AVP) - K-Pop','Avinguda del Parc','Blancs - Sweet Rebels','','Ritme i força per elevar la nostra essència coreana'),
('Dimecres 26','21.30h','21:30','Correfoc de la Colla Infantil dels Diables','Plaça de la Porxada','Diables de Granollers','','Infants acompanyats d''un adult. Roba de cotó i calçat tancat. Edat màxima 18 anys'),
('Dimecres 26','21.30h','21:30','Ni volent, volem (TB26PTF) - Concert de versions','Plaça de Folch i Torres','Blancs - Tribuneres','','Amb NiNi i punxadiscos tribunero'),
('Dimecres 26','21.56h','21:56','La Vinilada - Música dels 60-70-80-90 amb vinils','Plaça de l''Església','Blaus - Vinilada 33RPM','','Rock, pop, soul, reggae... festa retro!'),
('Dimecres 26','22h','22:00','Disco Inferno XS (HE26PCS)','Plaça de Pau Casals','Blancs - Blancs to hell','','Vine a gaudir de bona música amb DJ Posaxa!'),
('Dimecres 26','22h','22:00','Balles a plaça - Dansa tradicional i folk','Plaça de Perpinyà','Esbart Dansaire','','Amb el grup Semproniana'),
('Dimecres 26','22h','22:00','Ball del Drac Petit de Granollers','Plaça de la Porxada','Drac de Granollers','',''),
('Dimecres 26','22.30h','22:30','L''inCUCAció (CU26PRX) - La Cuca dels Blancs crema la Porxada','Plaça de la Porxada','Blancs - La Cuca dels Blancs','','Foc, Folk i Rock!'),
('Dimecres 26','23h','23:00','Disco Inferno (CB26AVP) - DJ Office','Avinguda del Parc','Blancs','','La festa més picant de l''Aeroport Blanc Amador Galí'),
('Dimecres 26','23h','23:00','MAYDAY! Arriba l''Hòstia! (CB26PRX) - Concurs d''avions de paper','Plaça de la Porxada','Blancs','','Majors d''edat. El concurs d''avions de paper més absurd i emocionant!'),
('Dimecres 26','00.03h','24:03','La Caseta dels Blaus - DJ QK','Plaça de Maluquer i Salvador','Blaus - Ànima Blava','','ACHO GRN ES OTRA COSAA'),
('Dimecres 26','00.59h','24:59','Toc de sometent - Correbars nocturn','Anselm Clavé (davant Museu)','Blaus - Blaucops','5€ (beguda i obsequi)','Majors de 18 anys'),

-- DIJOUS 27
('Dijous 27','10h','10:00','Concurs de Ball K-Pop + K-Pop Random Dance (SR27APL)','Roca Umbert. L''Aplegador','Blancs - Sweet Rebels','','Vine al centre de la pista i gaudeix del K-Pop amb tota la comunitat'),
('Dijous 27','10.06h','10:06','Blautxalla infantil - Jocs infantils','Parc del Congost','Blaus - Colles Infantils','','On cada joc és una nova aventura'),
('Dijous 27','11.30h','11:30','Saltaran Espurnes (EP27SKT) - Patinet i skate','Parc del Congost (Skate Park)','Blancs - Espurnes','','Vine amb el teu patinet o skate al circuit de les Espurnes Blanques!'),
('Dijous 27','14h','14:00','Dinar blankarra (BK27RCV) - Dinar, bingo i ambient','Roca Umbert. Plaça dels Recanvis','Blancs - Blankarras','8€','Majors de 18 anys. Inscripcions a @blankarras_fm'),
('Dijous 27','17h','17:00','Fragments de Llum (AM27PEX) - Taller de vitralls','Plaça del Peix','Blancs - Anònimament','3€','Majors de 16 anys. Inscripcions 30 min abans. Límit 2 tiquets per persona'),
('Dijous 27','17.01h','17:01','Punk in the Park - Prèvia','Plaça Pau Casals','Blaus - Blau Punks','','Zona punkids, barra i photocall'),
('Dijous 27','17.02h','17:02','Ruta del Celtillo - 5è correbars','Plaça Pau Casals','Blaus - Blauceltes','','Majors de 18 anys. Inscripcions dissabte 23 a pl. Església a partir de les 16h'),
('Dijous 27','17.30h','17:30','El Tardet (BV27PTF) - Prèvia del pregó','Plaça de Folch i Torres','Blancs - Blanqarivm','','Concert amb D''Lokos i DJ MOPP'),
('Dijous 27','17.34h','17:34','Cúmbia als porcs amb Pachamusta i Martí d''Endemic','Plaça de Perpinyà','Blaus - Culdesac','','Cumbia surrealista'),
('Dijous 27','18h','18:00','Cerimònia del Pregó de la Festa Major','Plaça de la Porxada','Comissió de la Festa Major','','Tronada d''inici i cercavila dels elements festius de la ciutat'),
('Dijous 27','19h','19:00','Entrada a plaça - Ball parlat dels Diables, pilar caminat Xics, ball Colom, Donzelles, Mulassa, Gegants, Drac','Plaça de la Porxada','Comissió de la Festa Major','','Seguici festiu complet!'),
('Dijous 27','20h','20:00','Pregó de Festa Major - Colla dels Blancs (guanyadora 2025)','Plaça de la Porxada','Comissió de la Festa Major','','Encesa de la traca i cant de La Guimbada'),
('Dijous 27','20.58h','20:58','Punk in the Park - Concert','Plaça Pau Casals','Blaus - Blau Punks','','Amb Storb, Tangana i Última Tormenta'),
('Dijous 27','20.59h','20:59','Sopar al Jardí del Cucut','Plaça de la Corona','Blaus - Fòssils','9€','Pots sopar, jugar i gaudir. Tiquets a partir de les 20h'),
('Dijous 27','21h','21:00','Vola amb nosaltres: 15 anys de la comitiva del Ganxet (CG27TRD)','Rambla de Tarradellas','Blancs - La Comitiva del Ganxet','15€','Sopar i gran espectacle a bord de l''avió ganxet. Tiquets a Villà Viatges'),
('Dijous 27','21h','21:00','Blanch Electrònic | Boarding (HB27MLQ1)','Plaça de Maluquer i Salvador','Blancs - Hardblancs','','Sunset i pista oberta. Autoritzat l''enlairament del house'),
('Dijous 27','21h','21:00','Correfoc de la Colla Jove dels Diables de Granollers','Plaça de la Porxada','Diables de Granollers','','Joves acompanyats d''un adult. Roba de cotó i calçat apte pel foc. Edat màxima 18 anys'),
('Dijous 27','21.45h','21:45','Ball del Drac Petit de Granollers','Plaça de la Porxada','Drac de Granollers','',''),
('Dijous 27','22.30h','22:30','Espectacle Qui cu qui que quina - Cia. Nom Provisional (circ)','Parc de Torras Villà','Ajuntament de Granollers','','Espectacle de circ'),
('Dijous 27','22.30h','22:30','Blanch Electrònic | On Time (HB27MLQ2) - Entrepans gurmet','Plaça de Maluquer i Salvador','Blancs - Hardblancs','5€ (sopar)','Turbines i Basslines sincronitzades. Opció vegana, vegetariana i sense gluten'),
('Dijous 27','22.57h','22:57','Sortida dels Toros Embolats','Plaça de la Caserna','Blaus - Toros Embolats','','Amb el Provechoso, l''Afgano, el Molaria i la vaca Divina'),
('Dijous 27','23h','23:00','Rècord QuinnEss? - Balla amb les Guapes','Carrer d''Anselm Clavé','Blancs - Guapes','','Rècord d''altura ballant!'),
('Dijous 27','23.04h','23:04','BlausÈxits - Repàs dels grans èxits musicals dels Blaus','Plaça de la Corona','Blaus - Memòria Blava / La Piula Musical','',''),
('Dijous 27','00h','24:00','Blanch Electrònic | On time (HB27MLQ3)','Plaça de Maluquer i Salvador','Blancs - Hardblancs','','Pressió sonora en augment. Assolim altitud de groove'),
('Dijous 27','00h','24:00','Versots: Crítica satírica sobre l''actualitat local','Plaça de la Porxada','Diables de Granollers','',''),
('Dijous 27','00h','24:00','Concert amb Buhos i Mina Ritz Live Band','Avinguda del Parc','Ajuntament de Granollers','',''),
('Dijous 27','1.02h','25:02','Concert amb Uri Gheller y los Cucharas','Plaça de Perpinyà','Blaus - Vermutaires','',''),
('Dijous 27','2h','26:00','Blanch Electrònic | Delayed (HB27MLQ4)','Plaça de Maluquer i Salvador','Blancs - Hardblancs','','240 km/h sense possibilitat d''aterratge'),

-- DIVENDRES 28
('Divendres 28','10.09h','10:09','Som Farretes - Jocs, activitats, tallers i cercavila','Plaça de Perpinyà','Blaus - Farretes','','El món meravellós de Farretes t''espera!'),
('Divendres 28','11h','11:00','Matinal de competicions: futbolí, dòmino, escacs i tennis taula','Plaça de la Corona','Comissió de la Festa Major','',''),
('Divendres 28','12h','12:00','Tronada de migdia','Plaça de la Porxada','Ajuntament de Granollers','','A càrrec de la Pirotècnia Alto Palancia'),
('Divendres 28','12.15h','12:15','Cercavila de Festa Major amb els gegants de la ciutat','Plaça de la Porxada','Amics dels Gegants i Capgrossos','',''),
('Divendres 28','13h','13:00','Balls de protocol dels gegants de la ciutat','Plaça de la Porxada','Amics dels Gegants i Capgrossos','',''),
('Divendres 28','14h','14:00','Arrossada popular','Parc de Torras Villà','Comissió de la Festa Major','7€','Paella, pa i postres'),
('Divendres 28','16h','16:00','Correaigua infantil (CA28PRX1)','Plaça de la Porxada','Blancs - Correaigua','','Inundem l''Aeroport Blanc Amador Galí'),
('Divendres 28','16.31h','16:31','La Tribuna - ones radiofòniques','Sala Francesc Tarafa','Blaus - B.A.R.','','Producte radiofònic sense processar'),
('Divendres 28','16.59h','16:59','Cercavila Gegantons fins a l''estirada de corda infantil','Plaça de la Porxada','Blaus - Gegantons','',''),
('Divendres 28','17h','17:00','Assaig a la fresca - Xics de Granollers','Plaça de l''Església','Xics de Granollers','','Vine i enfaixa''t amb nosaltres! #35xics'),
('Divendres 28','17.03h','17:03','Laboratori de pocions màgiques','Plaça de Perpinyà','Blaus - Guita Xica','','Entre ampolletes, colors i molta imaginació'),
('Divendres 28','17.07h','17:07','Sortides del Tren Blau de Ponent','Plaça de Maluquer i Salvador','Blaus - Amics de Ponent','1€','Fes una volta pel país de les meravelles'),
('Divendres 28','17.36h','17:36','1r Campionat interdimensional de castells de cartes','Sala Francesc Tarafa','Blaus - Irregulars Blaus','',''),
('Divendres 28','17.55h','17:55','Inici K''Hagum Tour Fest - Música en directe i sopar','Sala Francesc Tarafa','Blaus - K''HagumTot','7€','Amb Zesc, DJ NocturN & DJ LeTung, Sinestèsia, Laia Llach i Tiger Menja Zebra'),
('Divendres 28','18.02h','18:02','28è Concurs de Cuina de Peix Blau i Bacallà','Plaça de les Olles','Blaus - Fòssils','','Inscripcions a les 18h. Cal portar el plat cuinat. Bases a @peixblauibacalla'),
('Divendres 28','18.30h','18:30','Ballada de sardanes de Festa Major','Plaça de la Porxada','Agrupació Sardanista','','Amb la cobla Ciutat de Granollers'),
('Divendres 28','18.33h','18:33','Festa de l''escuma','Plaça de Perpinyà','Blaus - Guita Xica','','Un mar d''escuma meravellós!'),
('Divendres 28','19h','19:00','Estirada de corda infantil','Carrer d''Anselm Clavé','Comissió de la Festa Major','','De 6 a 12 anys i entre 1,15m i 1,65m. Cal guants i calçat tancat'),
('Divendres 28','19.30h','19:30','Estirada de corda (adults)','Carrer d''Anselm Clavé','Comissió de la Festa Major','','A partir de 13 anys i 1,65m. Cal guants i calçat tancat'),
('Divendres 28','20h','20:00','Concert familiar d''Ambauka - Quinze són Qüinze','Avinguda del Parc','Ajuntament de Granollers','',''),
('Divendres 28','20h','20:00','L''auca del Sr. Pera amb Joan Pera','Teatre Auditori de Granollers','Teatre Auditori','','Entrades a escenagran.cat'),
('Divendres 28','20h','20:00','FIMAC: sopar i concert amb Funk Power Station (FM28CSN)','Plaça de la Caserna','Blancs - FIMAC','','Sopar a les 20.30h. Funk que fa tremolar la pista'),
('Divendres 28','20.30h','20:30','Sortida de la Gralla de Foc dels Blaus i la Guspira dels Blancs','Plaça de la Porxada','Blancs i Blaus','',''),
('Divendres 28','21h','21:00','Correfoc de la Colla Gran dels Diables de Granollers','Plaça de la Porxada','Diables de Granollers','','Adults. Roba de cotó i calçat apte pel foc. Menors amb adult'),
('Divendres 28','22h','22:00','Observació del cel nocturn (AB28CMF)','Camp Municipal de futbol Primer de Maig','Blancs - Astroblancs','','Circuit tancat, sense reserva prèvia'),
('Divendres 28','22.04h','22:04','Blues a l''altra banda del mirall - Balta Bordoy & The Bad Boys','Plaça de Perpinyà','Blaus - Blaus Brothers','','Blues autèntic, vins, formatges i meravelles'),
('Divendres 28','22.30h','22:30','Espectacle White Bottom de Ramiro Vergaz - Circ','Parc de Torras Villà','Ajuntament de Granollers','','Espectacle de circ'),
('Divendres 28','22.30h','22:30','Ball del Drac de Granollers','Plaça de la Porxada','Drac de Granollers','',''),
('Divendres 28','23h','23:00','Correaigua dels 40 anys (CA28PRX2)','Plaça de la Porxada','Blancs - Correaigua','','Inundem l''Aeroport Blanc Amador Galí'),
('Divendres 28','23.30h','23:30','La Gran Burrada - Sortida nocturna de la Mulassa','Plaça de Maluquer i Salvador','L''Olla dels Pobres - Mulassa','','Amb la xaranga Bandsonats'),
('Divendres 28','23.30h','23:30','Timbalada dels Diables','Plaça de la Porxada','Diables de Granollers','',''),
('Divendres 28','23.56h','23:56','Concert Final K''Hagum Tour Fest - Joan Colomo i Also Starring DJ','Plaça de l''Església','Blaus - K''HagumTot','',''),
('Divendres 28','00h','24:00','Manifestació: Volem l''aeroport, al centre! (CB28OLL)','Plaça de les Olles','Blancs','','Estem tips de desplaçar-nos!'),
('Divendres 28','00h','24:00','Concert amb Maruja Limón, Triquell i DJ Beverly Hits','Avinguda del Parc','Ajuntament de Granollers','',''),
('Divendres 28','00.01h','24:01','Nit Blava amb DJ K-ZU i Nàtura b2b Charly B','Plaça de la Porxada','Blaus','','La nit més boja, la nit més blava!'),

-- DISSABTE 29
('Dissabte 29','10h','10:00','Bricks Blancs - Blocs de construcció, bèsties i festa! (BB29MLQ)','Plaça de Maluquer i Salvador','Blancs - Bricks Blancs','',''),
('Dissabte 29','10h','10:00','Cartes al vol (CT29GRA1) - Magic, One Piece, Lorcana i Pokemon','GRA. Equipament Juvenil','Blancs - Carta Blanca','',''),
('Dissabte 29','10.06h','10:06','Jocs de rol','Parc de Torras Villà','Blaus - Club de Rol Menrood','','Cada partida és una porta a un nou món'),
('Dissabte 29','10.30h','10:30','Circuit d''aventura, tirolina i rocòdrom','Parc de Ponent','Agrupació Excursionista de Granollers','','Fins a les 14h'),
('Dissabte 29','11h','11:00','Llançament de rajoles infantil (fins a 12 anys)','Parc del Congost','Comissió de la Festa Major','','Acte no competitiu'),
('Dissabte 29','12h','12:00','Tronada de migdia','Plaça de la Porxada','Ajuntament de Granollers','','A càrrec de la Pirotècnia Alto Palancia'),
('Dissabte 29','12.15h','12:15','La Convidada - Rebuda als gegants de la Vila de Sitges','Plaça de la Porxada','Amics dels Gegants i Capgrossos','',''),
('Dissabte 29','12.30h','12:30','Llançament de rajoles (a partir de 13 anys)','Parc de Congost','Comissió de la Festa Major','','A partir de 13 anys i d''1,60m d''alçada'),
('Dissabte 29','14h','14:00','Botifarrada blanca (BF29PTV)','Parc de Torras Villà','Blancs - Botifarrada','7€','La clàssica, la de sempre, la millor botifarra. Tiquets a partir de les 12h'),
('Dissabte 29','16h','16:00','Granollers Globus Cup (PN29CNY) - Competició de globus','Plaça de Barangé','Blancs - Paranoia','','Competició 1 vs 1. 3 categories per edat'),
('Dissabte 29','16h','16:00','Observació del Sol amb telescopis (AB29CCM1)','Plaça de Can Comas','Blancs - Astroblancs','','Circuit tancat, sense reserva prèvia'),
('Dissabte 29','16.30h','16:30','Sabar Show (TG29PTF) - Danses tradicionals del Senegal','Plaça de Folch i Torres','Blancs - Teranga','','Exhibició de danses, begudes africanes i sabors del continent'),
('Dissabte 29','16.57h','16:57','Trobada de Ball de Bastons','Plaça de la Corona','Blaus - Ball de Bastons','','Recorregut fins a la Porxada'),
('Dissabte 29','17h','17:00','Torneig TCG (CT29GRA2) - Magic, One Piece, Pokemon i Lorcana','GRA. Equipament Juvenil','Blancs - Carta Blanca','','Porta la teva baralla i fes-te amb la victòria'),
('Dissabte 29','17.03h','17:03','Sortides del Tren Blau de Ponent','Plaça de Maluquer i Salvador','Blaus - Amics de Ponent','1€','Fes una volta pel país de les meravelles'),
('Dissabte 29','17.30h','17:30','La Convidada - Cercavila gegants de Sitges i de la ciutat','Plaça de la Porxada','Amics dels Gegants i Capgrossos','',''),
('Dissabte 29','18h','18:00','Ballada de sardanes amb l''Orquestra Maravella','Avinguda del Parc','Ajuntament de Granollers','',''),
('Dissabte 29','18h','18:00','Taller de telescopis (AB29CCM2)','Plaça de Can Comas','Blancs - Astroblancs','','Porta el teu telescopi! Aprendrem a usar-lo correctament'),
('Dissabte 29','18.04h','18:04','Exhibició de la trobada del Ball de Bastons','Plaça de la Porxada','Blaus - Ball de Bastons','','Les bastorenes arriben a plaça!'),
('Dissabte 29','18.30h','18:30','Passada de rajoles infantil','Carrer d''Anselm Clavé','Comissió de la Festa Major','','Fins a 12 anys i entre 1 i 1,60m. Guants obligatoris'),
('Dissabte 29','19h','19:00','La Convidada - Mostra de balls i comiat als gegants de Sitges','Plaça de la Porxada','Amics dels Gegants i Capgrossos','',''),
('Dissabte 29','19.30h','19:30','Passada de rajoles (adults)','Carrer d''Anselm Clavé','Comissió de la Festa Major','','A partir de 13 anys o 1,60m. Guants obligatoris'),
('Dissabte 29','19.30h','19:30','Estirada de llengua (LL29ESG) - Concurs lingüístic','Plaça de l''Església','Blancs - Llenguts','','Veniu a jugar amb la llengua! Inscripcions a @llenguts.blancs de l''1 al 20 d''agost'),
('Dissabte 29','20h','20:00','Concert amb l''Orquestra Maravella','Parc de Torras Villà','Ajuntament de Granollers','',''),
('Dissabte 29','20h','20:00','Hamlet amb Albert Pla i en Peyu','Teatre Auditori de Granollers','Teatre Auditori','','Entrades a escenagran.cat'),
('Dissabte 29','20h','20:00','Pujades en globus aerostàtic (CB29CNY)','Plaça de Barangé','Blancs','','Vine a veure l''Aeroport des de les altures!'),
('Dissabte 29','20.30h','20:30','Sortida de la Guspira dels Blancs i la Gralla de Foc dels Blaus','Plaça de la Porxada','Blancs i Blaus','',''),
('Dissabte 29','21h','21:00','Correfoc de la Colla Gran dels Diables de Granollers','Plaça de la Porxada','Diables de Granollers','','Roba de cotó i calçat apte pel foc. Menors amb adult'),
('Dissabte 29','21.52h','21:52','El pas pel món de les meravelles - Gralla Jove i Guita Jove','Plaça de la Corona','Blaus - Gralla Jove i Guita Jove','','Espectacle de foc, música i relat'),
('Dissabte 29','22h','22:00','Ball amb l''Orquestra Maravella','Parc de Torras Villà','Ajuntament de Granollers','',''),
('Dissabte 29','22h','22:00','Indie Blancs vol. 2 (IN29PRC) - Allison Darwin i DJ Indie Cool','Plaça de Perpinyà','Blancs - Indie Blancs','',''),
('Dissabte 29','22h','22:00','Observació del cel nocturn (AB29CCM3)','Plaça de Can Comas','Blancs - Astroblancs','','Circuit tancat, sense reserva prèvia'),
('Dissabte 29','22.30h','22:30','Volat''s del Guateque! (YE29ESG) - Música dels 60s','Plaça de l''Església','Blancs - Blancs Yeyé','','La música ens farà volar allà on desitgem!'),
('Dissabte 29','22.30h','22:30','Ball del Drac de Granollers','Plaça de la Porxada','Drac de Granollers','',''),
('Dissabte 29','23h','23:00','Correaigua (CA29PRX)','Plaça de la Porxada','Blancs - Correaigua','','Inundem l''Aeroport Blanc Amador Galí'),
('Dissabte 29','23.30h','23:30','Timbalada dels Diables','Plaça de la Porxada','Diables de Granollers','',''),
('Dissabte 29','23.58h','23:58','Festa dels 1.000 litres','Plaça de Maluquer i Salvador','Blaus - Foteu-li Canya','2€','Ni el Barreter Boig s''hauria atrevit a tant'),
('Dissabte 29','00h','24:00','Concert amb Boom Boom Fighters i DJ Lia Jensen (CB29PRX)','Plaça de la Porxada','Blancs','','Dancehall, flow i carisma'),
('Dissabte 29','00h','24:00','Concert amb Jimband i Versión Imposible','Avinguda del Parc','Ajuntament de Granollers','',''),
('Dissabte 29','0.02h','24:02','ContraFesta - L''autèntica meravella','Plaça de Maluquer i Salvador','Blaus - Ànima Blava','',''),
('Dissabte 29','1h','25:00','Final de festa amb Dalessandro Deejay (CB29ESG)','Plaça de l''Església','Blancs','','La fera de la taula de mescles'),

-- DIUMENGE 30
('Diumenge 30','9.56h','09:56','Les Puntaires de Granollers ens trobem','Plaça de la Porxada','Blaus - Col·lectiu l''Embolic','','El so dels boixets, parada obligada al país de les meravelles'),
('Diumenge 30','11h','11:00','Missa solemne de Festa Major','Parròquia de Sant Esteve de Granollers','Parròquia de Sant Esteve','','Benedicció i presentació dels nous registres de l''orgue JM Ruera'),
('Diumenge 30','12h','12:00','Tronada de migdia','Plaça de la Porxada','Ajuntament de Granollers','','A càrrec de la Pirotècnia Alto Palancia'),
('Diumenge 30','12.15h','12:15','Diada castellera de Festa Major','Plaça de la Porxada','Xics de Granollers','','Castellers de Sabadell, Marrecs de Salt i Xics de Granollers #35xics'),
('Diumenge 30','15h','15:00','Dinar de Festa Major - Arrossada Xics','Roca Umbert. Nau Dents de Serra','Xics de Granollers','11-12€ sòcies / 7-8€ infants','Arrossada. Amanida + arròs + beguda'),
('Diumenge 30','16h','16:00','Acaba bé la Festa amb els Xics! Balla i participa','Roca Umbert. Pl. del Cotó','Xics de Granollers','','Deixa''t endur i balla! #35xics'),
('Diumenge 30','16.04h','16:04','L''hora de la Papallona','C. Anselm Clavé / Plaça de la Corona','Blaus','','Comparteix l''experiència al país de les meravelles'),
('Diumenge 30','16.29h','16:29','La Tribuna - ones radiofòniques','Sala Francesc Tarafa','Blaus - B.A.R.','','Producte radiofònic sense processar'),
('Diumenge 30','17.06h','17:06','Gran prèvia del Seguici - Omplim el Palau','Plaça de la Corona','Blaus - Front Blau','','Ole le, ola la, anem al palau blau!'),
('Diumenge 30','17.30h','17:30','Ball de Donzelles de Granollers','Plaça de la Porxada','Esbart Dansaire','','Es recomana haver assistit a l''assaig del dimecres 26'),
('Diumenge 30','18h','18:00','Seguici dels rajolers','Plaça de la Corona','Comissió de la Festa Major','','Recorregut fins al Palau d''Esports'),
('Diumenge 30','19h','19:00','Concurs de rajolers','Palau d''Esports','Comissió de la Festa Major','','L''acte central de la Festa Major de Blancs i Blaus!'),
('Diumenge 30','19.30h','19:30','Cantada d''havaneres amb Llops de Mar','Parc de Torras Villà','Ajuntament de Granollers','','Hi haurà rom cremat fins exhaurir existències'),
('Diumenge 30','21.30h','21:30','La traca dels 1.000 metres','Carrer d''Anselm Clavé','Diables de Granollers','','Recorregut per pl. Perpinyà, pl. Maluquer, c. Anselm Clavé i pl. Corona'),
('Diumenge 30','22.30h','22:30','Castell de focs - Pirotècnia Valenciana (guanyadora Trofeu Blancs i Blaus)','Parc Firal','Ajuntament de Granollers','','Concurs Internacional de Focs Artificials Ciutat de Tarragona'),
('Diumenge 30','00h','24:00','Veredicte de la colla guanyadora','Plaça de la Porxada','Comissió de la Festa Major','','El moment més esperat de la Festa Major!'),
('Diumenge 30','0.15h','24:15','Petons, abraçades i intercanvi de mocadors - Festa de cloenda','Plaça de Barangé','Ajuntament de Granollers','','Festa de cloenda amb Blancs i Blaus');
